module.exports = [
  "Hey cutie! 😘 Your smile is brighter than my future!",
  "Are you a parking ticket? Because you've got FINE written all over you! 😏",
  "Do you like science? Because we've got chemistry! 🔬",
  "Are you a magician? Because whenever I look at you, everyone else disappears! ✨",
  "Is your name Google? Because you've got everything I've been searching for! 🔍",
  "Are you made of copper and tellurium? Because you're Cu-Te! 💕",
  "Do you have a map? I keep getting lost in your eyes! 🗺️",
  "Are you a camera? Because every time I look at you, I smile! 📸",
  "Is your dad a baker? Because you're a cutie pie! 🥧",
  "Do you like camping? Because you're in-tents! ⛺",
  "Are you a time traveler? Because I can see you in my future! ⏰",
  "Is your name Wi-Fi? Because I'm feeling a connection! 📶",
  "Are you a bank loan? Because you've got my interest! 💰",
  "Are you a parking meter? Because I can see you have my heart! 💓",
  "Is your name Ariel? Because we were mermaid for each other! 🧜‍♀️",
  "Are you a fruit? Because you're a peach! 🍑",
  "Do you like coffee? Because you're brewing something special! ☕",
  "Are you a keyboard? Because you're just my type! ⌨️",
  "Is your name Cinderella? Because I can see this evening is going to be magical! 👑",
  "Do you like pizza? Because you're a slice of heaven! 🍕",
  "Are you a parking meter? Because I can see you have my heart! ❤️",
  "Is your name Google? Because you've got everything I've been searching for! 🔎",
  "Are you a time traveler? Because I can see you in my future! 🚀",
  "Is your name Wi-Fi? Because I'm feeling a connection! 📡",
  "Are you a bank loan? Because you've got my interest! 🏦",
  "Do you like science? Because we've got chemistry! 🔬",
  "Are you a parking meter? Because I can see you have my heart! 💖",
  "Is your name Ariel? Because we were mermaid for each other! 🌊",
  "Are you a fruit? Because you're a peach! 🍑",
  "Do you like coffee? Because you're brewing something special! ☕",
  "Are you a keyboard? Because you're just my type! 💻",
  "Is your name Cinderella? Because I can see this evening is going to be magical! ✨",
  "Hey beautiful! 🌹 Your eyes are like stars in the night sky!",
  "Are you a rainbow? Because you make my world colorful! 🌈",
  "Do you believe in love at first sight? Because I do now! 💘",
  "Are you a diamond? Because you're rare and precious! 💎",
  "Is your name Netflix? Because I could watch you all day! 📺",
  "Are you a shooting star? Because you make all my wishes come true! ⭐",
  "Do you like math? Because you're the solution to all my problems! ➗",
  "Are you a butterfly? Because you make my heart flutter! 🦋",
  "Is your name Spotify? Because you're music to my ears! 🎵",
  "Are you a sunset? Because you're absolutely breathtaking! 🌅",
  "Do you like gardening? Because you're growing on me! 🌱",
  "Are you a chocolate? Because you're sweet and irresistible! 🍫",
  "Is your name Instagram? Because I can't stop looking at you! 📱",
  "Are you a rainbow? Because you make my world colorful! 🌈",
  "Do you believe in love at first sight? Because I do now! 💘",
  "Are you a diamond? Because you're rare and precious! 💎",
  "Is your name Netflix? Because I could watch you all day! 📺",
  "Are you a shooting star? Because you make all my wishes come true! ⭐",
  "Do you like math? Because you're the solution to all my problems! ➗",
  "Are you a butterfly? Because you make my heart flutter! 🦋",
  "Is your name Spotify? Because you're music to my ears! 🎵",
  "Are you a sunset? Because you're absolutely breathtaking! 🌅",
  "Do you like gardening? Because you're growing on me! 🌱",
  "Are you a chocolate? Because you're sweet and irresistible! 🍫",
  "Is your name Instagram? Because I can't stop looking at you! 📱",
  "Are you a parking ticket? Because you've got FINE written all over you! 🚗",
  "Do you like pizza? Because you're a slice of heaven! 🍕",
  "Are you a parking meter? Because I can see you have my heart! 💕",
  "Is your name Google? Because you've got everything I've been searching for! 🔍",
  "Are you a parking ticket? Because you've got FINE written all over you! 🎫",
  "Do you like camping? Because you're in-tents! ⛺",
  "Are you a time traveler? Because I can see you in my future! ⏰",
  "Is your name Wi-Fi? Because I'm feeling a connection! 📶",
  "Are you a bank loan? Because you've got my interest! 💰",
  "Do you like science? Because we've got chemistry! 🧪",
  "Are you a parking meter? Because I can see you have my heart! 💓",
  "Is your name Ariel? Because we were mermaid for each other! 🧜‍♀️",
  "Are you a fruit? Because you're a peach! 🍑",
  "Do you like coffee? Because you're brewing something special! ☕",
  "Are you a keyboard? Because you're just my type! ⌨️",
  "Is your name Cinderella? Because I can see this evening is going to be magical! 👑",
  "Are you a parking ticket? Because you've got FINE written all over you! 🚗",
  "Do you like pizza? Because you're a slice of heaven! 🍕",
  "Are you a parking meter? Because I can see you have my heart! ❤️",
  "Is your name Google? Because you've got everything I've been searching for! 🔎",
  "Are you a parking ticket? Because you've got FINE written all over you! 🎫",
  "Do you like camping? Because you're in-tents! 🏕️",
  "Are you a time traveler? Because I can see you in my future! 🚀",
  "Is your name Wi-Fi? Because I'm feeling a connection! 📡",
  "Are you a bank loan? Because you've got my interest! 🏦",
  "Do you like science? Because we've got chemistry! 🔬",
  "Are you a parking meter? Because I can see you have my heart! 💖",
  "Is your name Ariel? Because we were mermaid for each other! 🌊",
  "Are you a fruit? Because you're a peach! 🍑",
  "Do you like coffee? Because you're brewing something special! ☕",
  "Are you a keyboard? Because you're just my type! 💻",
  "Is your name Cinderella? Because I can see this evening is going to be magical! ✨",
  "Hey beautiful! 🌹 Your eyes are like stars in the night sky!",
  "Are you a rainbow? Because you make my world colorful! 🌈",
  "Do you believe in love at first sight? Because I do now! 💘",
  "Are you a diamond? Because you're rare and precious! 💎",
  "Is your name Netflix? Because I could watch you all day! 📺",
  "Are you a shooting star? Because you make all my wishes come true! ⭐",
  "Do you like math? Because you're the solution to all my problems! ➗",
  "Are you a butterfly? Because you make my heart flutter! 🦋",
  "Is your name Spotify? Because you're music to my ears! 🎵",
  "Are you a sunset? Because you're absolutely breathtaking! 🌅",
  "Do you like gardening? Because you're growing on me! 🌱",
  "Are you a chocolate? Because you're sweet and irresistible! 🍫",
  "Is your name Instagram? Because I can't stop looking at you! 📱",
  "Are you a rainbow? Because you make my world colorful! 🌈",
  "Do you believe in love at first sight? Because I do now! 💘",
  "Are you a diamond? Because you're rare and precious! 💎",
  "Is your name Netflix? Because I could watch you all day! 📺",
  "Are you a shooting star? Because you make all my wishes come true! ⭐",
  "Do you like math? Because you're the solution to all my problems! ➗",
  "Are you a butterfly? Because you make my heart flutter! 🦋",
  "Is your name Spotify? Because you're music to my ears! 🎵",
  "Are you a sunset? Because you're absolutely breathtaking! 🌅",
  "Do you like gardening? Because you're growing on me! 🌱",
  "Are you a chocolate? Because you're sweet and irresistible! 🍫",
  "Is your name Instagram? Because I can't stop looking at you! 📱",
  "Are you a rainbow? Because you make my world colorful! 🌈",
  "Do you believe in love at first sight? Because I do now! 💘",
  "Are you a diamond? Because you're rare and precious! 💎",
  "Is your name Netflix? Because I could watch you all day! 📺",
  "Are you a shooting star? Because you make all my wishes come true! ⭐",
  "Do you like math? Because you're the solution to all my problems! ➗",
  "Are you a butterfly? Because you make my heart flutter! 🦋",
  "Is your name Spotify? Because you're music to my ears! 🎵",
  "Are you a sunset? Because you're absolutely breathtaking! 🌅",
  "Do you like gardening? Because you're growing on me! 🌱",
  "Are you a chocolate? Because you're sweet and irresistible! 🍫",
  "Is your name Instagram? Because I can't stop looking at you! 📱",
  "Are you a parking ticket? Because you've got FINE written all over you! 🚗",
  "Do you like pizza? Because you're a slice of heaven! 🍕",
  "Are you a parking meter? Because I can see you have my heart! 💕",
  "Is your name Google? Because you've got everything I've been searching for! 🔍",
  "Are you a parking ticket? Because you've got FINE written all over you! 🎫",
  "Do you like camping? Because you're in-tents! ⛺",
  "Are you a time traveler? Because I can see you in my future! ⏰",
  "Is your name Wi-Fi? Because I'm feeling a connection! 📶",
  "Are you a bank loan? Because you've got my interest! 💰",
  "Do you like science? Because we've got chemistry! 🧪",
  "Are you a parking meter? Because I can see you have my heart! 💓",
  "Is your name Ariel? Because we were mermaid for each other! 🧜‍♀️",
  "Are you a fruit? Because you're a peach! 🍑",
  "Do you like coffee? Because you're brewing something special! ☕",
  "Are you a keyboard? Because you're just my type! ⌨️",
  "Is your name Cinderella? Because I can see this evening is going to be magical! 👑",
  "Are you a parking ticket? Because you've got FINE written all over you! 🚗",
  "Do you like pizza? Because you're a slice of heaven! 🍕",
  "Are you a parking meter? Because I can see you have my heart! ❤️",
  "Is your name Google? Because you've got everything I've been searching for! 🔎",
  "Are you a parking ticket? Because you've got FINE written all over you! 🎫",
  "Do you like camping? Because you're in-tents! 🏕️",
  "Are you a time traveler? Because I can see you in my future! 🚀",
  "Is your name Wi-Fi? Because I'm feeling a connection! 📡",
  "Are you a bank loan? Because you've got my interest! 🏦",
  "Do you like science? Because we've got chemistry! 🔬",
  "Are you a parking meter? Because I can see you have my heart! 💖",
  "Is your name Ariel? Because we were mermaid for each other! 🌊",
  "Are you a fruit? Because you're a peach! 🍑",
  "Do you like coffee? Because you're brewing something special! ☕",
  "Are you a keyboard? Because you're just my type! 💻",
  "Is your name Cinderella? Because I can see this evening is going to be magical! ✨",
  "Hey beautiful! 🌹 Your eyes are like stars in the night sky!",
  "Are you a rainbow? Because you make my world colorful! 🌈",
  "Do you believe in love at first sight? Because I do now! 💘",
  "Are you a diamond? Because you're rare and precious! 💎",
  "Is your name Netflix? Because I could watch you all day! 📺",
  "Are you a shooting star? Because you make all my wishes come true! ⭐",
  "Do you like math? Because you're the solution to all my problems! ➗",
  "Are you a butterfly? Because you make my heart flutter! 🦋",
  "Is your name Spotify? Because you're music to my ears! 🎵",
  "Are you a sunset? Because you're absolutely breathtaking! 🌅",
  "Do you like gardening? Because you're growing on me! 🌱",
  "Are you a chocolate? Because you're sweet and irresistible! 🍫",
  "Is your name Instagram? Because I can't stop looking at you! 📱",
  "Are you a rainbow? Because you make my world colorful! 🌈",
  "Do you believe in love at first sight? Because I do now! 💘",
  "Are you a diamond? Because you're rare and precious! 💎",
  "Is your name Netflix? Because I could watch you all day! 📺",
  "Are you a shooting star? Because you make all my wishes come true! ⭐",
  "Do you like math? Because you're the solution to all my problems! ➗",
  "Are you a butterfly? Because you make my heart flutter! 🦋",
  "Is your name Spotify? Because you're music to my ears! 🎵",
  "Are you a sunset? Because you're absolutely breathtaking! 🌅",
  "Do you like gardening? Because you're growing on me! 🌱",
  "Are you a chocolate? Because you're sweet and irresistible! 🍫",
  "Is your name Instagram? Because I can't stop looking at you! 📱",
  "Are you a rainbow? Because you make my world colorful! 🌈",
  "Do you believe in love at first sight? Because I do now! 💘",
  "Are you a diamond? Because you're rare and precious! 💎",
  "Is your name Netflix? Because I could watch you all day! 📺",
  "Are you a shooting star? Because you make all my wishes come true! ⭐",
  "Do you like math? Because you're the solution to all my problems! ➗",
  "Are you a butterfly? Because you make my heart flutter! 🦋",
  "Is your name Spotify? Because you're music to my ears! 🎵",
  "Are you a sunset? Because you're absolutely breathtaking! 🌅",
  "Do you like gardening? Because you're growing on me! 🌱",
  "Are you a chocolate? Because you're sweet and irresistible! 🍫",
  "Is your name Instagram? Because I can't stop looking at you! 📱",
  "Are you a parking ticket? Because you've got FINE written all over you! 🚗",
  "Do you like pizza? Because you're a slice of heaven! 🍕",
  "Are you a parking meter? Because I can see you have my heart! 💕",
  "Is your name Google? Because you've got everything I've been searching for! 🔍",
  "Are you a parking ticket? Because you've got FINE written all over you! 🎫",
  "Do you like camping? Because you're in-tents! ⛺",
  "Are you a time traveler? Because I can see you in my future! ⏰",
  "Is your name Wi-Fi? Because I'm feeling a connection! 📶",
  "Are you a bank loan? Because you've got my interest! 💰",
  "Do you like science? Because we've got chemistry! 🧪",
  "Are you a parking meter? Because I can see you have my heart! 💓",
  "Is your name Ariel? Because we were mermaid for each other! 🧜‍♀️",
  "Are you a fruit? Because you're a peach! 🍑",
  "Do you like coffee? Because you're brewing something special! ☕",
  "Are you a keyboard? Because you're just my type! ⌨️",
  "Is your name Cinderella? Because I can see this evening is going to be magical! 👑",
  "Are you a parking ticket? Because you've got FINE written all over you! 🚗",
  "Do you like pizza? Because you're a slice of heaven! 🍕",
  "Are you a parking meter? Because I can see you have my heart! ❤️",
  "Is your name Google? Because you've got everything I've been searching for! 🔎",
  "Are you a parking ticket? Because you've got FINE written all over you! 🎫",
  "Do you like camping? Because you're in-tents! 🏕️",
  "Are you a time traveler? Because I can see you in my future! 🚀",
  "Is your name Wi-Fi? Because I'm feeling a connection! 📡",
  "Are you a bank loan? Because you've got my interest! 🏦",
  "Do you like science? Because we've got chemistry! 🔬",
  "Are you a parking meter? Because I can see you have my heart! 💖",
  "Is your name Ariel? Because we were mermaid for each other! 🌊",
  "Are you a fruit? Because you're a peach! 🍑",
  "Do you like coffee? Because you're brewing something special! ☕",
  "Are you a keyboard? Because you're just my type! 💻",
  "Is your name Cinderella? Because I can see this evening is going to be magical! ✨",
  "Hey beautiful! 🌹 Your eyes are like stars in the night sky!",
  "Are you a rainbow? Because you make my world colorful! 🌈",
  "Do you believe in love at first sight? Because I do now! 💘",
  "Are you a diamond? Because you're rare and precious! 💎",
  "Is your name Netflix? Because I could watch you all day! 📺",
  "Are you a shooting star? Because you make all my wishes come true! ⭐",
  "Do you like math? Because you're the solution to all my problems! ➗",
  "Are you a butterfly? Because you make my heart flutter! 🦋",
  "Is your name Spotify? Because you're music to my ears! 🎵",
  "Are you a sunset? Because you're absolutely breathtaking! 🌅",
  "Do you like gardening? Because you're growing on me! 🌱",
  "Are you a chocolate? Because you're sweet and irresistible! 🍫",
  "Is your name Instagram? Because I can't stop looking at you! 📱",
  "Are you a rainbow? Because you make my world colorful! 🌈",
  "Do you believe in love at first sight? Because I do now! 💘",
  "Are you a diamond? Because you're rare and precious! 💎",
  "Is your name Netflix? Because I could watch you all day! 📺",
  "Are you a shooting star? Because you make all my wishes come true! ⭐",
  "Do you like math? Because you're the solution to all my problems! ➗",
  "Are you a butterfly? Because you make my heart flutter! 🦋",
  "Is your name Spotify? Because you're music to my ears! 🎵",
  "Are you a sunset? Because you're absolutely breathtaking! 🌅",
  "Do you like gardening? Because you're growing on me! 🌱",
  "Are you a chocolate? Because you're sweet and irresistible! 🍫",
  "Is your name Instagram? Because I can't stop looking at you! 📱"
];
