module.exports = [
  "Your face looks like it was on fire and someone tried to put it out with a fork! 🔥",
  "You're so ugly, when you were born, the doctor slapped your mother! 👶",
  "Your IQ is lower than your shoe size! 👟",
  "You're so dumb, you think Taco Bell is a Mexican phone company! 🌮",
  "Your face could scare a hungry dog away from a meat truck! 🐕",
  "You're so slow, you could win a race against a statue! 🏃‍♂️",
  "Your jokes are so bad, even dad jokes feel embarrassed! 😂",
  "You're so lazy, you consider breathing exercise! 😴",
  "Your fashion sense is so bad, even a blind person would be offended! 👕",
  "You're so forgetful, you probably forgot you're reading this! 🤔",
  "Your cooking is so bad, even Gordon Ramsay would cry! 👨‍🍳",
  "You're so clumsy, you could trip over a wireless charger! 🔌",
  "Your singing is so bad, even tone-deaf people feel sorry for you! 🎤",
  "You're so slow, you could win a race against a glacier! 🧊",
  "Your jokes are so old, even your grandparents think they're outdated! 👴",
  "You're so unlucky, even a four-leaf clover would avoid you! 🍀",
  "Your dance moves are so bad, even a robot would be embarrassed! 🤖",
  "You're so boring, even a dictionary is more interesting! 📚",
  "Your selfies are so bad, even a potato would be offended! 🥔",
  "You're so slow, you could win a race against a snail! 🐌",
  "Your face looks like it was on fire and someone tried to put it out with a fork! 🔥",
  "You're so ugly, when you were born, the doctor slapped your mother! 👶",
  "Your IQ is lower than your shoe size! 👟",
  "You're so dumb, you think Taco Bell is a Mexican phone company! 🌮",
  "Your face could scare a hungry dog away from a meat truck! 🐕",
  "You're so slow, you could win a race against a statue! 🏃‍♂️",
  "Your jokes are so bad, even dad jokes feel embarrassed! 😂",
  "You're so lazy, you consider breathing exercise! 😴",
  "Your fashion sense is so bad, even a blind person would be offended! 👕",
  "You're so forgetful, you probably forgot you're reading this! 🤔",
  "Your cooking is so bad, even Gordon Ramsay would cry! 👨‍🍳",
  "You're so clumsy, you could trip over a wireless charger! 🔌",
  "Your singing is so bad, even tone-deaf people feel sorry for you! 🎤",
  "You're so slow, you could win a race against a glacier! 🧊",
  "Your jokes are so old, even your grandparents think they're outdated! 👴",
  "You're so unlucky, even a four-leaf clover would avoid you! 🍀",
  "Your dance moves are so bad, even a robot would be embarrassed! 🤖",
  "You're so boring, even a dictionary is more interesting! 📚",
  "Your selfies are so bad, even a potato would be offended! 🥔",
  "You're so slow, you could win a race against a snail! 🐌",
  "Your face looks like it was on fire and someone tried to put it out with a fork! 🔥",
  "You're so ugly, when you were born, the doctor slapped your mother! 👶",
  "Your IQ is lower than your shoe size! 👟",
  "You're so dumb, you think Taco Bell is a Mexican phone company! 🌮",
  "Your face could scare a hungry dog away from a meat truck! 🐕",
  "You're so slow, you could win a race against a statue! 🏃‍♂️",
  "Your jokes are so bad, even dad jokes feel embarrassed! 😂",
  "You're so lazy, you consider breathing exercise! 😴",
  "Your fashion sense is so bad, even a blind person would be offended! 👕",
  "You're so forgetful, you probably forgot you're reading this! 🤔",
  "Your cooking is so bad, even Gordon Ramsay would cry! 👨‍🍳",
  "You're so clumsy, you could trip over a wireless charger! 🔌",
  "Your singing is so bad, even tone-deaf people feel sorry for you! 🎤",
  "You're so slow, you could win a race against a glacier! 🧊",
  "Your jokes are so old, even your grandparents think they're outdated! 👴",
  "You're so unlucky, even a four-leaf clover would avoid you! 🍀",
  "Your dance moves are so bad, even a robot would be embarrassed! 🤖",
  "You're so boring, even a dictionary is more interesting! 📚",
  "Your selfies are so bad, even a potato would be offended! 🥔",
  "You're so slow, you could win a race against a snail! 🐌",
  "Your face looks like it was on fire and someone tried to put it out with a fork! 🔥",
  "You're so ugly, when you were born, the doctor slapped your mother! 👶",
  "Your IQ is lower than your shoe size! 👟",
  "You're so dumb, you think Taco Bell is a Mexican phone company! 🌮",
  "Your face could scare a hungry dog away from a meat truck! 🐕",
  "You're so slow, you could win a race against a statue! 🏃‍♂️",
  "Your jokes are so bad, even dad jokes feel embarrassed! 😂",
  "You're so lazy, you consider breathing exercise! 😴",
  "Your fashion sense is so bad, even a blind person would be offended! 👕",
  "You're so forgetful, you probably forgot you're reading this! 🤔",
  "Your cooking is so bad, even Gordon Ramsay would cry! 👨‍🍳",
  "You're so clumsy, you could trip over a wireless charger! 🔌",
  "Your singing is so bad, even tone-deaf people feel sorry for you! 🎤",
  "You're so slow, you could win a race against a glacier! 🧊",
  "Your jokes are so old, even your grandparents think they're outdated! 👴",
  "You're so unlucky, even a four-leaf clover would avoid you! 🍀",
  "Your dance moves are so bad, even a robot would be embarrassed! 🤖",
  "You're so boring, even a dictionary is more interesting! 📚",
  "Your selfies are so bad, even a potato would be offended! 🥔",
  "You're so slow, you could win a race against a snail! 🐌",
  "Your face looks like it was on fire and someone tried to put it out with a fork! 🔥",
  "You're so ugly, when you were born, the doctor slapped your mother! 👶",
  "Your IQ is lower than your shoe size! 👟",
  "You're so dumb, you think Taco Bell is a Mexican phone company! 🌮",
  "Your face could scare a hungry dog away from a meat truck! 🐕",
  "You're so slow, you could win a race against a statue! 🏃‍♂️",
  "Your jokes are so bad, even dad jokes feel embarrassed! 😂",
  "You're so lazy, you consider breathing exercise! 😴",
  "Your fashion sense is so bad, even a blind person would be offended! 👕",
  "You're so forgetful, you probably forgot you're reading this! 🤔",
  "Your cooking is so bad, even Gordon Ramsay would cry! 👨‍🍳",
  "You're so clumsy, you could trip over a wireless charger! 🔌",
  "Your singing is so bad, even tone-deaf people feel sorry for you! 🎤",
  "You're so slow, you could win a race against a glacier! 🧊",
  "Your jokes are so old, even your grandparents think they're outdated! 👴",
  "You're so unlucky, even a four-leaf clover would avoid you! 🍀",
  "Your dance moves are so bad, even a robot would be embarrassed! 🤖",
  "You're so boring, even a dictionary is more interesting! 📚",
  "Your selfies are so bad, even a potato would be offended! 🥔",
  "You're so slow, you could win a race against a snail! 🐌",
  "Your face looks like it was on fire and someone tried to put it out with a fork! 🔥",
  "You're so ugly, when you were born, the doctor slapped your mother! 👶",
  "You're so dumb, you couldn't pour water out of a boot with instructions on the heel! 👢",
  "You're so slow, you could win a race against a statue! 🏃‍♂️",
  "Your face looks like it was carved by a blind sculptor! 🗿",
  "You're so ugly, even your shadow refuses to follow you! 👤",
  "You're so dumb, you think a quarterback is a refund! 🏈",
  "You're so slow, you could win a race against a tree! 🌳",
  "Your face looks like it was hit by a truck and then backed over! 🚛",
  "You're so ugly, even your mom has to tie a steak around your neck to get the dog to play with you! 🥩",
  "You're so dumb, you think a quarterback is a refund! 🏈",
  "You're so slow, you could win a race against a rock! 🪨",
  "Your face looks like it was carved by a drunk sculptor! 🗿",
  "You're so ugly, even your reflection runs away from you! 👤",
  "You're so dumb, you think a quarterback is a refund! 🏈",
  "You're so slow, you could win a race against a dead person! 💀",
  "Your face looks like it was hit by a train and then backed over! 🚂",
  "You're so ugly, even your mom has to tie a steak around your neck to get the dog to play with you! 🥩",
  "You're so dumb, you think a quarterback is a refund! 🏈",
  "You're so slow, you could win a race against a statue! 🏃‍♂️",
  "Your face looks like it was carved by a blind sculptor! 🗿",
  "You're so ugly, even your shadow refuses to follow you! 👤",
  "You're so dumb, you think a quarterback is a refund! 🏈",
  "You're so slow, you could win a race against a tree! 🌳",
  "Your face looks like it was hit by a truck and then backed over! 🚛",
  "You're so ugly, even your mom has to tie a steak around your neck to get the dog to play with you! 🥩",
  "You're so dumb, you think a quarterback is a refund! 🏈",
  "You're so slow, you could win a race against a rock! 🪨",
  "Your face looks like it was carved by a drunk sculptor! 🗿",
  "You're so ugly, even your reflection runs away from you! 👤",
  "You're so dumb, you think a quarterback is a refund! 🏈",
  "You're so slow, you could win a race against a dead person! 💀",
  "Your face looks like it was hit by a train and then backed over! 🚂",
  "You're so ugly, even your mom has to tie a steak around your neck to get the dog to play with you! 🥩",
  "You're so dumb, you think a quarterback is a refund! 🏈",
  "You're so slow, you could win a race against a statue! 🏃‍♂️",
  "Your face looks like it was carved by a blind sculptor! 🗿",
  "You're so ugly, even your shadow refuses to follow you! 👤",
  "You're so dumb, you think a quarterback is a refund! 🏈",
  "You're so slow, you could win a race against a tree! 🌳",
  "Your face looks like it was hit by a truck and then backed over! 🚛",
  "You're so ugly, even your mom has to tie a steak around your neck to get the dog to play with you! 🥩",
  "You're so dumb, you think a quarterback is a refund! 🏈",
  "You're so slow, you could win a race against a rock! 🪨",
  "Your face looks like it was carved by a drunk sculptor! 🗿",
  "You're so ugly, even your reflection runs away from you! 👤",
  "You're so dumb, you think a quarterback is a refund! 🏈",
  "You're so slow, you could win a race against a dead person! 💀",
  "Your face looks like it was hit by a train and then backed over! 🚂",
  "You're so ugly, even your mom has to tie a steak around your neck to get the dog to play with you! 🥩",
  "You're so dumb, you think a quarterback is a refund! 🏈",
  "You're so slow, you could win a race against a statue! 🏃‍♂️",
  "Your face looks like it was carved by a blind sculptor! 🗿",
  "You're so ugly, even your shadow refuses to follow you! 👤",
  "You're so dumb, you think a quarterback is a refund! 🏈",
  "You're so slow, you could win a race against a tree! 🌳",
  "Your face looks like it was hit by a truck and then backed over! 🚛",
  "You're so ugly, even your mom has to tie a steak around your neck to get the dog to play with you! 🥩",
  "You're so dumb, you think a quarterback is a refund! 🏈",
  "You're so slow, you could win a race against a rock! 🪨",
  "Your face looks like it was carved by a drunk sculptor! 🗿",
  "You're so ugly, even your reflection runs away from you! 👤",
  "You're so dumb, you think a quarterback is a refund! 🏈",
  "You're so slow, you could win a race against a dead person! 💀",
  "Your face looks like it was hit by a train and then backed over! 🚂",
  "You're so ugly, even your mom has to tie a steak around your neck to get the dog to play with you! 🥩",
  "You're so dumb, you think a quarterback is a refund! 🏈"
];
